//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/InputActions/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""dd03fb0a-ba07-461a-9dc8-1c4dc5506b13"",
            ""actions"": [
                {
                    ""name"": ""AttackNorth"",
                    ""type"": ""Button"",
                    ""id"": ""0a2ea968-0ff4-4d39-b5ee-fa02934cac43"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AttackSouth"",
                    ""type"": ""Button"",
                    ""id"": ""47db96a6-e562-484f-9ec4-5aac05885b9d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AttackEast"",
                    ""type"": ""Button"",
                    ""id"": ""05ce24d7-8039-475c-8de3-9856ec04fa33"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AttackWest"",
                    ""type"": ""Button"",
                    ""id"": ""e92496d2-fd68-4c21-9d19-8b9ec118a810"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c16bf5de-bc1b-4ba7-8e16-e049742415b3"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AttackNorth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""95208d28-a95f-4bae-9afd-988567e274d3"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AttackNorth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""850f8ad8-d032-4374-9c88-fca374bf2ae7"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AttackSouth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c104f24-2ad7-4498-97c3-30e8593b0af5"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AttackSouth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""520caaaa-7591-4bc5-9278-a53ccc2ddc9e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AttackEast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9eb34e88-378f-4689-9de6-1dc3e5a687d2"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AttackEast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f5627d03-6b99-4c2f-bd85-392b4b450a9e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AttackWest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e8d9a406-2032-45d4-9109-e60a5b49bffc"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AttackWest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_AttackNorth = m_Gameplay.FindAction("AttackNorth", throwIfNotFound: true);
        m_Gameplay_AttackSouth = m_Gameplay.FindAction("AttackSouth", throwIfNotFound: true);
        m_Gameplay_AttackEast = m_Gameplay.FindAction("AttackEast", throwIfNotFound: true);
        m_Gameplay_AttackWest = m_Gameplay.FindAction("AttackWest", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private IGameplayActions m_GameplayActionsCallbackInterface;
    private readonly InputAction m_Gameplay_AttackNorth;
    private readonly InputAction m_Gameplay_AttackSouth;
    private readonly InputAction m_Gameplay_AttackEast;
    private readonly InputAction m_Gameplay_AttackWest;
    public struct GameplayActions
    {
        private @PlayerInputActions m_Wrapper;
        public GameplayActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @AttackNorth => m_Wrapper.m_Gameplay_AttackNorth;
        public InputAction @AttackSouth => m_Wrapper.m_Gameplay_AttackSouth;
        public InputAction @AttackEast => m_Wrapper.m_Gameplay_AttackEast;
        public InputAction @AttackWest => m_Wrapper.m_Gameplay_AttackWest;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void SetCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterface != null)
            {
                @AttackNorth.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAttackNorth;
                @AttackNorth.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAttackNorth;
                @AttackNorth.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAttackNorth;
                @AttackSouth.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAttackSouth;
                @AttackSouth.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAttackSouth;
                @AttackSouth.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAttackSouth;
                @AttackEast.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAttackEast;
                @AttackEast.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAttackEast;
                @AttackEast.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAttackEast;
                @AttackWest.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAttackWest;
                @AttackWest.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAttackWest;
                @AttackWest.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAttackWest;
            }
            m_Wrapper.m_GameplayActionsCallbackInterface = instance;
            if (instance != null)
            {
                @AttackNorth.started += instance.OnAttackNorth;
                @AttackNorth.performed += instance.OnAttackNorth;
                @AttackNorth.canceled += instance.OnAttackNorth;
                @AttackSouth.started += instance.OnAttackSouth;
                @AttackSouth.performed += instance.OnAttackSouth;
                @AttackSouth.canceled += instance.OnAttackSouth;
                @AttackEast.started += instance.OnAttackEast;
                @AttackEast.performed += instance.OnAttackEast;
                @AttackEast.canceled += instance.OnAttackEast;
                @AttackWest.started += instance.OnAttackWest;
                @AttackWest.performed += instance.OnAttackWest;
                @AttackWest.canceled += instance.OnAttackWest;
            }
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);
    public interface IGameplayActions
    {
        void OnAttackNorth(InputAction.CallbackContext context);
        void OnAttackSouth(InputAction.CallbackContext context);
        void OnAttackEast(InputAction.CallbackContext context);
        void OnAttackWest(InputAction.CallbackContext context);
    }
}
